core/urls.py
from django.urls import path
from . import views

from django_filters.views import FilterView
from .models import Item

app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('product/<str:pk>/', views.product, name='product'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-to-cart/<str:pk>/', views.add_to_cart, name='add-to-cart'),
    path('add-coupon/', views.AddCoupon.as_view(), name='add-coupon'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('remove-from-cart/<str:pk>/',
         views.remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<str:pk>/',
         views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<str:payment_option>/',
         views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestFundView.as_view(), name='request-refund'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #     path('acc/login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('product/',
         FilterView.as_view(model=Item,                                               filterset_fields=['name', 'category']), name='product-filter'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db.models.signals import post_save
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Mens Shirt'),
    ('WA', 'Women Dress'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
    ('E', 'Electronics'),
    ('C', 'Computing devices'),
    ('N', 'Network devices'),
    ('F', 'Furniture'),
    ('FB', 'Food and Beverages'),
    ('U', 'Utensils'),
    ('P', 'Phones'),
    ('SH', 'Shoes'),
    ('BB', 'Baby Care'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

ADDRESS_CHOICES = (
    ('S', 'Shipping'),
    ('B', 'Billing'),
)


# class UserProfile(models.Model):
#     user = models.OneToOneField(
#         settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     stripe_customer_id = models.CharField(max_length=50, null=True, blank=True)
#     on_click_purchasing = models.BooleanField(default=False)

#     def __str__(self):
#         return self.user.username


class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    discount_price = models.DecimalField(
        blank=True, null=True, max_digits=5, decimal_places=2)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    description = models.TextField(max_length=1000, null=True, blank=True)
    additional_info = models.TextField(max_length=1000, null=True, blank=True)
    image = models.ImageField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'pk': self.pk
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={'pk': self.pk})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={'pk': self.pk})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, null=True, blank=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, null=True, blank=True)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, null=True, blank=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, null=True, blank=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, null=True, blank=True)
    being_delivered = models.BooleanField(default=False)
    recieved = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apparment_address = models.CharField(max_length=100, null=True)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=50)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES
                                    )
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    email = models.EmailField()
    reason = models.TextField()
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.pk}"


# def userprofile_reciever(sender, instance, created, *args, **kwargs):
#     if created:
#         userprofile = UserProfile.objects.create(user=instance)


# post_save.connect(userprofile_reciever, sender=settings.AUTH_USER_MODEL)

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, View
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib import messages
from django.conf import settings
from .models import Item, OrderItem, Order, Address, Payment, Coupon, Refund
from .forms import CheckoutForm, CouponForm, RefundForm, RegisterForm
from .filters import ItemFilter

import stripe
import random
import string
stripe.api_key = settings.STRIPE_SECRET_KEY


def create_ref_code():
    return "".join(random.choices(string.ascii_lowercase + string.digits, k=20))


class RegisterView(View):
    def get(self, *args, **kwargs):
        form = RegisterForm()
        context = {
            'form': form
        }
        return render(self.request, 'core/register.html', context)

    def post(self, *args, **kwargs):
        form = RegisterForm(self.request.POST or None)
        if form.is_valid():
            user = form.save()
            return redirect('account_login')
        else:
            messages.warning(self.request, 'The two passwords did not match')
            return redirect('core:register')


def logout_view(request):
    logout(request)
    return redirect('account_login')


class HomeView(ListView):
    model = Item
    paginate_by = 10
    filter_set = ItemFilter
    template_name = 'core/home-page.html'


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {'object': order}
            return render(self.request, 'core/order-summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, 'You do not have an  active order')
            return redirect('core:index')


def product(request, pk):
    item = Item.objects.get(pk=pk)
    extra_items = Item.objects.all()[3:5]
    context = {
        'item': item,
        'extra_items': extra_items
    }
    return render(request, 'core/product-page.html', context)


def is_valid_form(values):
    valid = True
    for field in values:
        if field == "":
            valid = False
    return valid


class CheckoutView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'couponform': CouponForm(),
                'DISPLAY_COUPON_FORM': True,
                'order': order
            }

            shipping_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='S',
                default=True
            )
            if shipping_address_qs.exists():
                context.update(
                    {'default_shipping_address': shipping_address_qs[0]})

            billing_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='B',
                default=True
            )
            if billing_address_qs.exists():
                context.update(
                    {'default_billing_address': billing_address_qs[0]})

            return render(self.request, 'core/checkout-page.html', context)
        except ObjectDoesNotExist:
            messages.info(self.request, 'You do not have an active order')
            return redirect("core:checkout")

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                use_default_shipping = form.cleaned_data.get(
                    'use_default_shipping')
                if use_default_shipping:
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='S',
                        default=True
                    )
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(
                            self.request, 'No default shipping address available')
                        return redirect('core:checkout')
                else:
                    shipping_address1 = form.cleaned_data.get(
                        'shipping_address')
                    shipping_address2 = form.cleaned_data.get(
                        'shipping_address2')
                    shipping_country = form.cleaned_data.get(
                        'shipping_country')
                    shipping_zip = form.cleaned_data.get('shipping_zip')

                    if is_valid_form([shipping_address1, shipping_country, shipping_zip]):
                        shipping_address = Address(
                            user=self.request.user,
                            street_address=shipping_address1,
                            apparment_address=shipping_address2,
                            country=shipping_country,
                            zip=shipping_zip,
                            address_type='S'
                        )
                        shipping_address.save()

                        order.shipping_address = shipping_address
                        order.save()

                        set_default_shipping = form.cleaned_data.get(
                            'set_default_shipping')
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()
                    else:
                        messages.info(
                            self.request, 'Please fill in the required fields')

                use_default_billing = form.cleaned_data.get(
                    'use_default_billing')
                same_billing_address = form.cleaned_data.get(
                    'same_billing_address')

                if same_billing_address:
                    billing_address = shipping_address
                    billing_address.pk = None
                    billing_address.save()
                    billing_address.address_type = 'B'
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()
                elif use_default_billing:
                    print('Using the default billing address')
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='B',
                        default=True
                    )
                    if address_qs.exists():
                        billing_address = address_qs[0]
                        order.billing_address = billing_address
                        order.save()
                    else:
                        messages.info(
                            self.request, 'No default billing address available')
                        return redirect('core:checkout')
                else:
                    print('User is entering a new billing address')
                    billing_address1 = form.cleaned_data.get(
                        'billing_address')
                    billing_address2 = form.cleaned_data.get(
                        'billing_address2')
                    billing_country = form.cleaned_data.get(
                        'billing_country')
                    billing_zip = form.cleaned_data.get('billing_zip')

                    if is_valid_form([billing_address1, billing_country, billing_zip]):
                        billing_address = Address(
                            user=self.request.user,
                            street_address=billing_address1,
                            apparment_address=billing_address2,
                            country=billing_country,
                            zip=billing_zip,
                            address_type='B'
                        )
                        billing_address.save()

                        order.billing_address = billing_address
                        order.save()

                        set_default_billing = form.cleaned_data.get(
                            'set_default_billing')
                        if set_default_billing:
                            billing_address.default = True
                            billing_address.save()
                    else:
                        messages.info(
                            self.request, 'Please fill in the required fields')

                payment_option = form.cleaned_data.get('payment_option')
                # redirect to selected payment method
                if payment_option == 'S':
                    return redirect("core:payment", payment_option="stripe")
                elif payment_option == 'P':
                    return redirect("core:payment", payment_option="paypal")
                else:
                    messages.warning(self.request, 'Invalid Payment Method')
                    return redirect("core:checkout")
            else:
                message.error(self.request, 'Please correct the errors below')
                return redirect("core:checkout")
        except ObjectDoesNotExist:
            messages.error(self.request, 'You do not have an active order')
            return redirect('core:order-summary')


class PaymentView(View):
    def get(self, *args, **kwargs):

templates/core/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

  <hr class="my-4">

  <!-- Social icons -->
  <div class="pb-4">
    <a href="https://www.facebook.com" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="https://twitter.com/@khosam4" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="https://www.youtube.com" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="https://github.com/kkthecompguy" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="https://instagram.com/homlo_khosam" target="_blank">
      <i class="fab fa-instagram mr-3"></i>
    </a>

    <a href="https://www.linkedin.com/in/kosam-omollo-4b0b6018a/" target="_blank">
      <i class="fab fa-linkedin mr-3"></i>
    </a>
  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2020 Copyright:
    <a href="/"> Allsafe Shop Limited</a>
  </div>
  <!--/.Copyright-->

</footer>
<!--/.Footer-->

templates/core/home-page.html
{% extends 'base.html' %}
{% load static %}

{% block head_title %}
Get the best products form the best retailers. #1 stop shop
{% endblock %}

{% block content %}
<style type="text/css">
  html,
  body,
  header,
  .carousel {
    height: 60vh;
  }

  @media (max-width: 740px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }
</style>

<!--Main layout-->
<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>

        </ul>
        <!-- Links -->

        <form action="" method="GET" class="form-inline">
          {% csrf_token %}
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">
        {% for item in object_list %}
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">

          <!--Card-->
          <div class="card h-100">

            <!--Card image-->
            <div class="view overlay">
              <img src="{{item.image.url}}" class="card-img-top" alt="">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5>{{item.get_category_display}}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{item.name}}
                    <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>
                  {% if item.discount_price %}
                  {{item.discount_price}}$
                  {% else %}
                  {{item.price}}$
                  {% endif %}
                </strong>
              </h4>

            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div>
        <!--Grid column-->
        {% endfor %}
      </div>
      <!-- Grid row -->
    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        <!--Arrow left-->
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number}}">{{ page_obj.number}}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
    <!--Pagination-->

  </div>
</main>
<!--Main layout-->

{% endblock %}

templates/core/navbar.html
{% load cart_template_tags %}
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'core:index' %}">
      <strong class="blue-text">Allsafe Shop</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <a class="nav-link waves-effect" href="{% url 'core:index' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li> -->
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }}</span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item px-2">
          <a href="" class="nav-link waves-effect">
            <span class="clearfix d-none d-sm-inline-block"><i class="fas fa-user"></i>{{request.user}}</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'core:logout' %}" class="nav-link waves-effect">
            <span class="clearfix d-none d-sm-inline-block">Logout</span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'account_login' %}" class="nav-link waves-effect">
            <span class="clearfix d-none d-sm-inline-block">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'core:register' %}" class="nav-link waves-effect">
            <span class="clearfix d-none d-sm-inline-block">SignUp</span>
          </a>
        </li>
        {% endif %}
      </ul>

    </div>

  </div>
</nav>
<!-- Navbar -->

templates/core/order-snippet.html
<!--Grid column-->
<div class="col-md-12 mb-4 mt-5">

  <!-- Heading -->
  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
  </h4>

  <!-- Cart -->
  <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.name}}</h6>
        <small class="text-muted">{{order_item.item.description}}</small>
      </div>
      <span class="text-muted">${{order_item.get_final_price}}</span>
    </li>
    {% endfor %}

    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{order.coupon.code}}</small>
      </div>
      <span class="text-success">-${{order.coupon.amount}}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
      <span>Total (USD)</span>
      <strong>${{order.get_total}}</strong>
    </li>
  </ul>
  <!-- Cart -->

  <!-- Promo code -->
  {% if DISPLAY_COUPON_FORM %}
  <form action="{% url 'core:add-coupon' %}" method="POST" class="card p-2">
    {% csrf_token %}
    <div class="input-group">
      {{couponform.code}}
      <div class="input-group-append">
        <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
      </div>
    </div>
  </form>
  {% endif %}
  <!-- Promo code -->

</div>
<!--Grid column-->

templates/core/order-summary.html
{% extends 'base.html' %}
{% load static %}

{% block head_title %}
Order Summary
{% endblock %}

{% block content %}
<style type="text/css">
  html,
  body,
  header,
  .carousel {
    height: 60vh;
  }

  @media (max-width: 740px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }
</style>

<!--Main layout-->
<main>
  <div class="container">
    <h3>Order Summary</h3>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Item Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total price</th>
          </tr>
        </thead>
        <tbody>
          {% if object.items %}
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter}}</th>
            <td>{{order_item.item.name}}</td>
            <td>{{order_item.item.price}}</td>
            <td>
              <span class="badge badge-primary">{{order_item.quantity}}</span>
              <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i class="fas fa-plus ml-2 mr-2"></i></a>
              <a href="{% url 'core:remove-single-item-from-cart' order_item.item.pk %}">
                <i class="fas fa-minus ml-2 mr-2"></i>
              </a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
              ${{order_item.get_total_discount_item_price}}
              <span class="badge badge-primary">saving ${{order_item.get_amount_saved}}</span>
              {% else %}
              {{order_item.get_total_item_price}}
              {% endif %}
            </td>
            <td>
              <a href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                <i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
          {% else %}
          <tr>
            <td colspan="4">Your cart is empty</td>
          </tr>
          <tr>
            <td colspan="4">
              <a href="/" class="btn btn-primary float-right">Continue shopping</a>
            </td>
          </tr>
          {% endif %}

          {% if object.coupon %}
          <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td colspan="5"><b>-${{object.coupon.amount}}</b></td>
          </tr>
          {% endif %}

          {% if object.get_total %}
          <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td colspan="5"><b>${{object.get_total}}</b></td>
          </tr>
          <tr>
            <td colspan="5">
              <a href="/checkout" class="btn btn-warning float-right ml-2">Proceed to checkout</a>
              <a href="/" class="btn btn-primary float-right">Continue shopping</a>
            </td>
          </tr>
          {% else %}
          <tr>
            <td colspan="5">
              <a href="/" class="btn btn-primary float-right">Continue shopping</a>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</main>
<!--Main layout-->

{% endblock %}

templates/core/request-refund.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}
Request Refund
{% endblock %}

{% block content %}

<!--Main layout-->
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h3>Request Refund</h3>
        <form action="" method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="Submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</main>
<!--Main layout-->

{% endblock %}